from __future__ import annotations

import json
import os
from pathlib import Path
import urllib.request

import yaml

CRD_URL = (
    "https://raw.githubusercontent.com/kubeflow/spark-operator/master/"
    "config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml"
)
CRD_PATH = Path("schemas/sparkoperator_crd.yaml")
SCHEMA_PATH = Path("schemas/spark_application_schema.json")


def main() -> None:
    CRD_PATH.parent.mkdir(parents=True, exist_ok=True)

    refresh = os.getenv("REFRESH_CRD", "0") == "1"
    if refresh or not CRD_PATH.exists():
        with urllib.request.urlopen(CRD_URL) as response:  # noqa: S310
            raw_yaml = response.read().decode("utf-8")
        CRD_PATH.write_text(raw_yaml, encoding="utf-8")
    else:
        raw_yaml = CRD_PATH.read_text(encoding="utf-8")

    crd = yaml.safe_load(raw_yaml)
    versions = crd.get("spec", {}).get("versions", [])

    target_version = None
    for version in versions:
        if version.get("name") == "v1beta2":
            target_version = version
            break

    if target_version is None and versions:
        target_version = versions[0]

    if target_version is None:
        raise RuntimeError("No CRD versions found in SparkApplication CRD")

    schema = target_version.get("schema", {}).get("openAPIV3Schema")
    if not schema:
        raise RuntimeError("No openAPIV3Schema found in SparkApplication CRD version")

    # Stabilize the root class name generated by datamodel-codegen.
    schema["title"] = "SparkoperatorV1beta2SparkApplication"

    SCHEMA_PATH.write_text(json.dumps(schema, indent=2), encoding="utf-8")
    print(f"Saved raw CRD to {CRD_PATH}")
    print(f"Saved extracted JSON schema to {SCHEMA_PATH}")


if __name__ == "__main__":
    main()
